--
-- PostgreSQL database dump
--

\restrict lhk3vPzvxEpK5Y4TfiBWTqSc4j6m6KHvIJkXeFxEeSaUaljMf1CHJ43gFpJxiRm

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Addresses" (
    "Id" bigint NOT NULL,
    "AddressLine1" text NOT NULL,
    "AddressLine2" text NOT NULL,
    "CountryId" integer NOT NULL,
    "StateId" integer NOT NULL,
    "CityId" integer NOT NULL,
    "PinCode" text NOT NULL,
    "Latitude" numeric(10,7) NOT NULL,
    "Longitude" numeric(10,7) NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Addresses" OWNER TO postgres;

--
-- Name: Addresses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Addresses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Addresses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AppointmentTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AppointmentTypes" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."AppointmentTypes" OWNER TO postgres;

--
-- Name: AppointmentTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AppointmentTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AppointmentTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Appointments" (
    "Id" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "PhysiotherapistId" bigint NOT NULL,
    "AppointmentDate" timestamp with time zone NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "AppointmentTypeId" integer NOT NULL,
    "StatusId" integer NOT NULL,
    "Reason" text NOT NULL,
    "Notes" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Appointments" OWNER TO postgres;

--
-- Name: Appointments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Appointments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Appointments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cities" (
    "Id" integer NOT NULL,
    "StateId" integer NOT NULL,
    "Name" text NOT NULL,
    "PinCode" text NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Cities" OWNER TO postgres;

--
-- Name: Cities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Countries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Countries" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Countries" OWNER TO postgres;

--
-- Name: Countries_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Countries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Countries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Employees" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Position" text NOT NULL,
    "Salary" numeric(10,2) NOT NULL
);


ALTER TABLE public."Employees" OWNER TO postgres;

--
-- Name: Employees_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Employees" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Employees_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Exercises" (
    "Id" bigint NOT NULL,
    "CategoryId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "Instructions" text NOT NULL,
    "VideoUrl" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Exercises" OWNER TO postgres;

--
-- Name: Exercises_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Exercises" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Exercises_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PatientAssessments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatientAssessments" (
    "Id" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "SessionId" bigint,
    "PhysiotherapistId" bigint NOT NULL,
    "AssessmentDate" timestamp with time zone NOT NULL,
    "ChiefComplaint" text NOT NULL,
    "CurrentCondition" text NOT NULL,
    "PainLevel" integer NOT NULL,
    "Diagnosis" text NOT NULL,
    "ClinicalNotes" text NOT NULL,
    "Recommendations" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PatientAssessments" OWNER TO postgres;

--
-- Name: PatientAssessments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatientAssessments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatientAssessments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PatientDocuments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatientDocuments" (
    "Id" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "DocumentTypeId" integer,
    "FileName" text NOT NULL,
    "StorageKey" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "ContentType" text NOT NULL,
    "UploadedBy" bigint NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PatientDocuments" OWNER TO postgres;

--
-- Name: PatientDocuments_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatientDocuments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatientDocuments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PatientMedicalHistories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PatientMedicalHistories" (
    "Id" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "DiagnosisDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PatientMedicalHistories" OWNER TO postgres;

--
-- Name: PatientMedicalHistories_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PatientMedicalHistories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PatientMedicalHistories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Patients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Patients" (
    "Id" bigint NOT NULL,
    "UserId" bigint,
    "PatientNumber" text NOT NULL,
    "AddressId" bigint NOT NULL,
    "RegistrationDate" timestamp with time zone NOT NULL,
    "ReferredBy" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Patients" OWNER TO postgres;

--
-- Name: Patients_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Patients" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Patients_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Roles" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Roles" OWNER TO postgres;

--
-- Name: Roles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Specializations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Specializations" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."Specializations" OWNER TO postgres;

--
-- Name: Specializations_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Specializations" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Specializations_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: States; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."States" (
    "Id" integer NOT NULL,
    "CountryId" integer NOT NULL,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."States" OWNER TO postgres;

--
-- Name: States_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."States" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."States_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TreatmentPlans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TreatmentPlans" (
    "Id" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "PhysiotherapistId" bigint NOT NULL,
    "AssessmentId" bigint NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "ExpectedEndDate" timestamp with time zone NOT NULL,
    "NumberOfSessions" integer NOT NULL,
    "Goal" text NOT NULL,
    "Notes" text NOT NULL,
    "StatusId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."TreatmentPlans" OWNER TO postgres;

--
-- Name: TreatmentPlans_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TreatmentPlans" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TreatmentPlans_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TreatmentSessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TreatmentSessions" (
    "Id" bigint NOT NULL,
    "AppointmentId" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "PhysiotherapistId" bigint NOT NULL,
    "TreatmentPlanId" bigint,
    "SessionDate" timestamp with time zone NOT NULL,
    "StartTime" interval NOT NULL,
    "EndTime" interval NOT NULL,
    "PainLevelBefore" integer NOT NULL,
    "PainLevelAfter" integer NOT NULL,
    "Notes" text NOT NULL,
    "StatusId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."TreatmentSessions" OWNER TO postgres;

--
-- Name: TreatmentSessions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TreatmentSessions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TreatmentSessions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TreatmentTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TreatmentTypes" (
    "Id" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "DefaultDurationMinutes" integer NOT NULL,
    "DefaultPrice" numeric(12,2) NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."TreatmentTypes" OWNER TO postgres;

--
-- Name: TreatmentTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TreatmentTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TreatmentTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserProfiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserProfiles" (
    "Id" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "GenderId" integer NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "ProfileImage" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "AddressId" bigint NOT NULL,
    "EmergencyContactName" text NOT NULL,
    "EmergencyContactPhone" text NOT NULL,
    "BloodGroupId" integer NOT NULL,
    "Occupation" text NOT NULL,
    "RegistrationDate" timestamp with time zone NOT NULL
);


ALTER TABLE public."UserProfiles" OWNER TO postgres;

--
-- Name: UserProfiles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserProfiles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserProfiles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: UserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserRoles" (
    "Id" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "RoleId" integer NOT NULL,
    "IsActive" boolean NOT NULL
);


ALTER TABLE public."UserRoles" OWNER TO postgres;

--
-- Name: UserRoles_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserRoles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserRoles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" bigint NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" character varying(500) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" bigint,
    "UpdatedBy" bigint
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: Addresses PK_Addresses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id");


--
-- Name: AppointmentTypes PK_AppointmentTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AppointmentTypes"
    ADD CONSTRAINT "PK_AppointmentTypes" PRIMARY KEY ("Id");


--
-- Name: Appointments PK_Appointments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: Cities PK_Cities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cities"
    ADD CONSTRAINT "PK_Cities" PRIMARY KEY ("Id");


--
-- Name: Countries PK_Countries; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Countries"
    ADD CONSTRAINT "PK_Countries" PRIMARY KEY ("Id");


--
-- Name: Employees PK_Employees; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Employees"
    ADD CONSTRAINT "PK_Employees" PRIMARY KEY ("Id");


--
-- Name: Exercises PK_Exercises; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Exercises"
    ADD CONSTRAINT "PK_Exercises" PRIMARY KEY ("Id");


--
-- Name: PatientAssessments PK_PatientAssessments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientAssessments"
    ADD CONSTRAINT "PK_PatientAssessments" PRIMARY KEY ("Id");


--
-- Name: PatientDocuments PK_PatientDocuments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientDocuments"
    ADD CONSTRAINT "PK_PatientDocuments" PRIMARY KEY ("Id");


--
-- Name: PatientMedicalHistories PK_PatientMedicalHistories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientMedicalHistories"
    ADD CONSTRAINT "PK_PatientMedicalHistories" PRIMARY KEY ("Id");


--
-- Name: Patients PK_Patients; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("Id");


--
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- Name: Specializations PK_Specializations; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Specializations"
    ADD CONSTRAINT "PK_Specializations" PRIMARY KEY ("Id");


--
-- Name: States PK_States; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."States"
    ADD CONSTRAINT "PK_States" PRIMARY KEY ("Id");


--
-- Name: TreatmentPlans PK_TreatmentPlans; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreatmentPlans"
    ADD CONSTRAINT "PK_TreatmentPlans" PRIMARY KEY ("Id");


--
-- Name: TreatmentSessions PK_TreatmentSessions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreatmentSessions"
    ADD CONSTRAINT "PK_TreatmentSessions" PRIMARY KEY ("Id");


--
-- Name: TreatmentTypes PK_TreatmentTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreatmentTypes"
    ADD CONSTRAINT "PK_TreatmentTypes" PRIMARY KEY ("Id");


--
-- Name: UserProfiles PK_UserProfiles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfiles"
    ADD CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id");


--
-- Name: UserRoles PK_UserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserRoles"
    ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Addresses_CityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Addresses_CityId" ON public."Addresses" USING btree ("CityId");


--
-- Name: IX_Addresses_CountryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Addresses_CountryId" ON public."Addresses" USING btree ("CountryId");


--
-- Name: IX_Addresses_StateId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Addresses_StateId" ON public."Addresses" USING btree ("StateId");


--
-- Name: IX_Cities_StateId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Cities_StateId" ON public."Cities" USING btree ("StateId");


--
-- Name: IX_Exercises_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Exercises_CategoryId" ON public."Exercises" USING btree ("CategoryId");


--
-- Name: IX_PatientDocuments_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PatientDocuments_PatientId" ON public."PatientDocuments" USING btree ("PatientId");


--
-- Name: IX_PatientDocuments_UploadedBy; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PatientDocuments_UploadedBy" ON public."PatientDocuments" USING btree ("UploadedBy");


--
-- Name: IX_PatientMedicalHistories_PatientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PatientMedicalHistories_PatientId" ON public."PatientMedicalHistories" USING btree ("PatientId");


--
-- Name: IX_Patients_AddressId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Patients_AddressId" ON public."Patients" USING btree ("AddressId");


--
-- Name: IX_Patients_PatientNumber; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Patients_PatientNumber" ON public."Patients" USING btree ("PatientNumber");


--
-- Name: IX_Patients_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Patients_UserId" ON public."Patients" USING btree ("UserId");


--
-- Name: IX_Roles_Name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Roles_Name" ON public."Roles" USING btree ("Name");


--
-- Name: IX_States_CountryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_States_CountryId" ON public."States" USING btree ("CountryId");


--
-- Name: IX_TreatmentTypes_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_TreatmentTypes_CategoryId" ON public."TreatmentTypes" USING btree ("CategoryId");


--
-- Name: IX_UserProfiles_AddressId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserProfiles_AddressId" ON public."UserProfiles" USING btree ("AddressId");


--
-- Name: IX_UserProfiles_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UserProfiles_UserId" ON public."UserProfiles" USING btree ("UserId");


--
-- Name: IX_UserRoles_UserId_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_UserRoles_UserId_RoleId" ON public."UserRoles" USING btree ("UserId", "RoleId");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- Name: Addresses FK_Addresses_Cities_CityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES public."Cities"("Id");


--
-- Name: Addresses FK_Addresses_Countries_CountryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("Id");


--
-- Name: Addresses FK_Addresses_States_StateId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Addresses"
    ADD CONSTRAINT "FK_Addresses_States_StateId" FOREIGN KEY ("StateId") REFERENCES public."States"("Id");


--
-- Name: Cities FK_Cities_States_StateId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cities"
    ADD CONSTRAINT "FK_Cities_States_StateId" FOREIGN KEY ("StateId") REFERENCES public."States"("Id") ON DELETE CASCADE;


--
-- Name: Exercises FK_Exercises_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Exercises"
    ADD CONSTRAINT "FK_Exercises_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- Name: PatientDocuments FK_PatientDocuments_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientDocuments"
    ADD CONSTRAINT "FK_PatientDocuments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- Name: PatientDocuments FK_PatientDocuments_Users_UploadedBy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientDocuments"
    ADD CONSTRAINT "FK_PatientDocuments_Users_UploadedBy" FOREIGN KEY ("UploadedBy") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: PatientMedicalHistories FK_PatientMedicalHistories_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PatientMedicalHistories"
    ADD CONSTRAINT "FK_PatientMedicalHistories_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- Name: Patients FK_Patients_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "FK_Patients_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES public."Addresses"("Id") ON DELETE CASCADE;


--
-- Name: Patients FK_Patients_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "FK_Patients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id");


--
-- Name: States FK_States_Countries_CountryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."States"
    ADD CONSTRAINT "FK_States_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries"("Id") ON DELETE CASCADE;


--
-- Name: TreatmentTypes FK_TreatmentTypes_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TreatmentTypes"
    ADD CONSTRAINT "FK_TreatmentTypes_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- Name: UserProfiles FK_UserProfiles_Addresses_AddressId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfiles"
    ADD CONSTRAINT "FK_UserProfiles_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES public."Addresses"("Id") ON DELETE CASCADE;


--
-- Name: UserProfiles FK_UserProfiles_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserProfiles"
    ADD CONSTRAINT "FK_UserProfiles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict lhk3vPzvxEpK5Y4TfiBWTqSc4j6m6KHvIJkXeFxEeSaUaljMf1CHJ43gFpJxiRm

